server:
  servlet:
    context-path: /api/v1
spring:
  application:
    name: grion-server
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
openai:
  api:
    url: https://api.openai.com/v1/moderations
jwt:
  access-token-expiration: 2592000000
  refresh-token-expiration: 5184000000
springdoc:
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
cors:
  allowed-origins:
    - http://localhost:3000
